erDiagram

    USERS {
        int id PK
        string full_name
        string email
        string password_hash
        string role
        datetime created_at
    }

    AI_MODELS {
        int id PK
        string name
        string provider
        string model_key
        boolean is_active
        datetime created_at
    }

    ATTACK_SCENARIOS {
        int id PK
        string title
        string description
        string attack_type
        text prompt_text
        boolean is_predefined
        int created_by FK
        datetime created_at
    }

    TEST_RUNS {
        int id PK
        int user_id FK
        int model_id FK
        text custom_prompt
        string status
        datetime created_at
        datetime completed_at
    }

    TEST_RUN_SCENARIOS {
        int id PK
        int test_run_id FK
        int scenario_id FK
    }

    TEST_RESULTS {
        int id PK
        int test_run_id FK
        int scenario_id FK
        text raw_response
        text masked_response
        boolean is_sensitive
        int safety_score
        string risk_level
        string result
        text analysis_summary
        text detected_issues
        datetime created_at
    }

    USERS ||--o{ ATTACK_SCENARIOS : creates
    USERS ||--o{ TEST_RUNS : runs

    AI_MODELS ||--o{ TEST_RUNS : tested_on

    TEST_RUNS ||--o{ TEST_RUN_SCENARIOS : contains
    ATTACK_SCENARIOS ||--o{ TEST_RUN_SCENARIOS : included_in

    TEST_RUNS ||--o{ TEST_RESULTS : generates
    ATTACK_SCENARIOS ||--o{ TEST_RESULTS : tested_as
